# app/domains/properties/models.py

"""
Domain: Properties
Tables: properties, property_features, property_feature_map
Enums: PropertyType, ListingStatus, ApprovalStatus, FeatureCategory

Design decisions:
  - Amenities are rows, not boolean columns (Decision 7).
    Adding "Rooftop Terrace" = INSERT one row, zero schema changes.
  - ListingStatus (rent/sale/short_let/lease) is separate from ApprovalStatus.
    ListingStatus = what the listing is FOR (never changes after creation).
    ApprovalStatus = the listing's LIFECYCLE (changes through state machine).
  - Only approval_status = 'published' AND expires_at > now() is public (Rule 2).
  - address_hidden = True means only city/state shown publicly (Decision 10).
  - expires_at is set to now() + 30 days when published (Decision 4).
  - latitude/longitude are NOT NULL — every property needs coordinates for search.
  - price uses Numeric(15,2) — exact decimal, no floating-point rounding.
  - All CHECK constraints from SQL schema v9.2 are re-declared here so
    Alembic detects them and includes them in autogenerated migrations.
  - hybrid_property used for computed properties that appear in queries.
    @property used for display-only computed properties.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime, timezone
from decimal import Decimal
from typing import TYPE_CHECKING, Optional

import sqlalchemy as sa
from sqlalchemy import (
    Boolean, CheckConstraint, DateTime, ForeignKey, Integer, Numeric,
    String, Text, UniqueConstraint, text, func,
)
from sqlalchemy.dialects.postgresql import DOUBLE_PRECISION, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.ext.hybrid import hybrid_property

from app.db.base import Base
from app.db.mixins import UUIDMixin, TimestampMixin, CreatedAtMixin

if TYPE_CHECKING:
    from app.domains.analytics.models import PropertyAnalytics
    from app.domains.bookings.models import AgentAvailability, Booking
    from app.domains.media.models import PropertyImage, VirtualTour
    from app.domains.messaging.models import Conversation
    from app.domains.reviews.models import Review
    from app.domains.search.models import Favorite, SavedSearch, SearchHistory
    from app.domains.users.models import User


# ─── Enums ───────────────────────────────────────────────────────────────────

class PropertyType(str, enum.Enum):
    """Physical type of the property."""
    APARTMENT = "apartment"
    HOUSE = "house"
    DUPLEX = "duplex"
    STUDIO = "studio"
    COMMERCIAL = "commercial"
    OFFICE = "office"


class ListingStatus(str, enum.Enum):
    """
    What the agent is offering the property for.
    Set at creation time. Does not change through the approval lifecycle.
    """
    RENT = "rent"
    SALE = "sale"
    SHORT_LET = "short_let"
    LEASE = "lease"


class ApprovalStatus(str, enum.Enum):
    """
    Full property lifecycle state machine.

    10 states, 19 valid transitions.
    Only PUBLISHED + not expired = appears in public search (Rule 2).

    States:
      DRAFT          — agent editing, never submitted
      PENDING_REVIEW — submitted, admin hasn't decided yet
      APPROVED       — admin approved, agent can publish
      REJECTED       — admin rejected, never was public
      PUBLISHED      — live, appears in search
      RESERVED       — agent reserved for a specific renter
      RENTED         — tenancy active, no longer available
      SOLD           — sold (for sale listings)
      ARCHIVED       — expired or manually archived
      SUSPENDED      — admin pulled a published listing offline

    Removed from ERD v9.2:
      EXPIRED  — use ARCHIVED instead (Celery sets ARCHIVED when expires_at passes)
      FLAGGED  — handled by reports table + admin action (not a property state)

    Valid transitions (enforced in property_service.py):
      DRAFT           → PENDING_REVIEW  (agent submits)
      PENDING_REVIEW  → APPROVED        (admin approves)
      PENDING_REVIEW  → REJECTED        (admin rejects)
      REJECTED        → PENDING_REVIEW  (agent resubmits after fixing)
      APPROVED        → PUBLISHED       (agent publishes)
      APPROVED        → DRAFT           (agent edits before publishing)
      PUBLISHED       → RESERVED        (agent marks reserved)
      PUBLISHED       → RENTED          (agent marks rented directly)
      PUBLISHED       → SOLD            (agent marks sold)
      PUBLISHED       → ARCHIVED        (Celery: expires_at passed)
      PUBLISHED       → PENDING_REVIEW  (agent edits published listing)
      PUBLISHED       → SUSPENDED       (admin pulls offline)
      RESERVED        → RENTED          (tenancy confirmed)
      RESERVED        → PUBLISHED       (reservation falls through)
      RENTED          → ARCHIVED        (auto-archived)
      SOLD            → ARCHIVED        (auto-archived)
      SUSPENDED       → PUBLISHED       (admin re-enables)
      SUSPENDED       → ARCHIVED        (admin archives)
      ARCHIVED        → PENDING_REVIEW  (agent republishes)
    """
    DRAFT = "draft"
    PENDING_REVIEW = "pending_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    PUBLISHED = "published"
    RESERVED = "reserved"
    RENTED = "rented"
    SOLD = "sold"
    ARCHIVED = "archived"
    SUSPENDED = "suspended"


class FeatureCategory(str, enum.Enum):
    """
    Groups features for UI display and search filtering.

    Seed data (in Alembic migration):
      amenities → Furnished, Air Conditioning, Generator, Water Supply, Parking
      rules     → Pet Allowed, No Smoking, Family Only, Female Only
      building  → Balcony, Garden, Elevator, Swimming Pool, Gym
      security  → Security Guard, CCTV, Gated Estate, Intercom
    """
    AMENITIES = "amenities"
    RULES = "rules"
    BUILDING = "building"
    SECURITY = "security"


# ─── SQLAlchemy Enum column types ────────────────────────────────────────────

_property_type_col = sa.Enum(
    PropertyType,
    name="property_type",
    values_callable=lambda obj: [e.value for e in obj],
)

_listing_status_col = sa.Enum(
    ListingStatus,
    name="listing_status",
    values_callable=lambda obj: [e.value for e in obj],
)

_approval_status_col = sa.Enum(
    ApprovalStatus,
    name="approval_status",
    values_callable=lambda obj: [e.value for e in obj],
)

_feature_category_col = sa.Enum(
    FeatureCategory,
    name="feature_category",
    values_callable=lambda obj: [e.value for e in obj],
)


# ─── Property Model ──────────────────────────────────────────────────────────

class Property(Base, UUIDMixin, TimestampMixin):
    """
    Core listing model. The most field-heavy model in the platform.

    Table: properties

    Three FK references to users:
      owner_id          — the agent who owns the listing
      rented_by_user_id — the renter who rented through the platform (nullable)
      approved_by       — the admin who approved the listing (nullable)

    Each requires explicit foreign_keys= in relationship() to avoid
    SQLAlchemy's "ambiguous foreign key" error.
    """

    __tablename__ = "properties"

    # ── Ownership ─────────────────────────────────────────────────────────────
    owner_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="The agent who created this listing.",
    )
    rented_by_user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="Set when property is rented through the platform. NULL for offline rentals.",
    )

    # ── Core listing fields ───────────────────────────────────────────────────
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    price: Mapped[Decimal] = mapped_column(
        Numeric(15, 2), nullable=False,
        comment="Always positive — enforced by chk_price CHECK constraint.",
    )
    currency: Mapped[str] = mapped_column(
        String(3), nullable=False,
        server_default=text("'NGN'"),
        default="NGN",
    )
    property_type: Mapped[PropertyType] = mapped_column(
        _property_type_col, nullable=False,
    )
    status: Mapped[ListingStatus] = mapped_column(
        _listing_status_col, nullable=False,
        comment="What the agent is offering: rent, sale, short_let, lease.",
    )

    # ── Lifecycle ─────────────────────────────────────────────────────────────
    approval_status: Mapped[ApprovalStatus] = mapped_column(
        _approval_status_col, nullable=False,
        server_default=text("'draft'"),
        default=ApprovalStatus.DRAFT,
        index=True,
    )
    rejection_reason: Mapped[Optional[str]] = mapped_column(
        String(500), nullable=True,
        comment="Set by admin when rejecting. Required when approval_status=rejected.",
    )
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    rented_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
        comment="Stamped when agent marks property as rented.",
    )
    expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
        index=True,
        comment=(
            "Set to now() + 30 days when published (Decision 4). "
            "Celery listing_expiry job archives when this passes."
        ),
    )

    # ── Address ───────────────────────────────────────────────────────────────
    street: Mapped[Optional[str]] = mapped_column(String(300), nullable=True)
    building_number: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    formatted_address: Mapped[Optional[str]] = mapped_column(
        String(512), nullable=True,
        comment="Cached from Google Geocoding API. Not fetched on every request.",
    )
    city: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    state: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    latitude: Mapped[float] = mapped_column(
        DOUBLE_PRECISION, nullable=False,
        comment="Used for PostGIS radius search and Google Places API nearby lookup.",
    )
    longitude: Mapped[float] = mapped_column(DOUBLE_PRECISION, nullable=False)
    address_hidden: Mapped[bool] = mapped_column(
        Boolean, nullable=False,
        server_default=text("false"),
        default=False,
        comment=(
            "When True, only city/state shown publicly (Decision 10). "
            "Full address revealed only to users with a confirmed booking."
        ),
    )

    # ── Physical details ──────────────────────────────────────────────────────
    bedrooms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    bathrooms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    master_bedrooms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    toilets: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    area_size: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(10, 2), nullable=True,
        comment="Floor area in square metres.",
    )

    # ── Promotion flags ───────────────────────────────────────────────────────
    featured: Mapped[bool] = mapped_column(
        Boolean, nullable=False,
        server_default=text("false"),
        default=False,
        comment="Admin-set. Featured listings appear in promoted slots.",
    )
    verified: Mapped[bool] = mapped_column(
        Boolean, nullable=False,
        server_default=text("false"),
        default=False,
        comment="Admin-set. Shows a verified badge on the listing.",
    )

    # ── Table constraints (mirrors SQL schema v9.2) ───────────────────────────
    __table_args__ = (
        CheckConstraint("price > 0", name="chk_price"),
        CheckConstraint("bedrooms IS NULL OR bedrooms >= 0", name="chk_bedrooms"),
        CheckConstraint("bathrooms IS NULL OR bathrooms >= 0", name="chk_bathrooms"),
        CheckConstraint(
            "master_bedrooms IS NULL OR master_bedrooms >= 0",
            name="chk_master_bedrooms",
        ),
        CheckConstraint("toilets IS NULL OR toilets >= 0", name="chk_toilets"),
        CheckConstraint("area_size IS NULL OR area_size > 0", name="chk_area_size"),
        CheckConstraint(
            "latitude >= -90 AND latitude <= 90",
            name="chk_latitude",
        ),
        CheckConstraint(
            "longitude >= -180 AND longitude <= 180",
            name="chk_longitude",
        ),
        # NOTE: The PostGIS GiST spatial index is NOT declared here.
        # Alembic autogenerate cannot detect GiST indexes.
        # It is written manually in the initial Alembic migration:
        #   op.execute("""
        #     CREATE INDEX idx_properties_location ON properties USING GiST (
        #         ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
        #     )
        #   """)
    )

    # ── Relationships ─────────────────────────────────────────────────────────

    # Three FKs to users — all need explicit foreign_keys= to avoid ambiguity
    owner: Mapped[User] = relationship(
        "User",
        back_populates="properties",
        foreign_keys=[owner_id],
    )
    rented_by_user: Mapped[Optional[User]] = relationship(
        "User",
        back_populates="rented_properties",
        foreign_keys=[rented_by_user_id],
    )
    approved_by_admin: Mapped[Optional[User]] = relationship(
        "User",
        foreign_keys=[approved_by],
        uselist=False,
    )

    # Bookings for this property (no cascade — bookings are permanent records)
    bookings: Mapped[list[Booking]] = relationship(
        "Booking",
        back_populates="listing",
    )

    # Property reviews (no cascade — reviews are permanent records)
    reviews: Mapped[list[Review]] = relationship(
        "Review",
        back_populates="listing",
    )

    # Media: images and 360° tours (cascade — belongs to property)
    images: Mapped[list[PropertyImage]] = relationship(
        "PropertyImage",
        back_populates="listing",
        cascade="all, delete-orphan",
        order_by="PropertyImage.display_order",
    )
    virtual_tours: Mapped[list[VirtualTour]] = relationship(
        "VirtualTour",
        back_populates="listing",
        cascade="all, delete-orphan",
        order_by="VirtualTour.display_order",
    )

    # Raw analytics events (no cascade — analytics are permanent records)
    analytics: Mapped[list[PropertyAnalytics]] = relationship(
        "PropertyAnalytics",
        back_populates="listing",
    )

    # Agent calendar slots for this property (cascade — belongs to property)
    availability_slots: Mapped[list[AgentAvailability]] = relationship(
        "AgentAvailability",
        back_populates="listing",
        cascade="all, delete-orphan",
    )

    # Conversations started about this property (no cascade)
    conversations: Mapped[list[Conversation]] = relationship(
        "Conversation",
        back_populates="listing",
    )

    # Saved / favourited by renters (cascade — disposable link)
    favorites: Mapped[list[Favorite]] = relationship(
        "Favorite",
        back_populates="listing",
        cascade="all, delete-orphan",
    )

    # Dynamic amenities via junction table
    # secondary="property_feature_map" uses the TABLE NAME (string) so
    # SQLAlchemy finds it after all models are loaded. No import needed.
    features: Mapped[list[PropertyFeature]] = relationship(
        "PropertyFeature",
        secondary="property_feature_map",
        back_populates="properties",
        lazy="selectin",
    )

    # ── Computed properties: hybrid (usable in queries) ───────────────────────

    @hybrid_property
    def is_published(self) -> bool:
        """Python: property.is_published"""
        return self.approval_status == ApprovalStatus.PUBLISHED

    @is_published.expression
    def is_published(cls):
        """SQL: WHERE Property.is_published"""
        return cls.approval_status == ApprovalStatus.PUBLISHED

    @hybrid_property
    def is_expired(self) -> bool:
        """Python: property.is_expired"""
        if self.expires_at is None:
            return False
        return datetime.now(tz=timezone.utc) > self.expires_at

    @is_expired.expression
    def is_expired(cls):
        """SQL: WHERE Property.is_expired"""
        return sa.and_(
            cls.expires_at.isnot(None),
            cls.expires_at < func.now(),
        )

    @hybrid_property
    def is_publicly_visible(self) -> bool:
        """
        Rule 2: Published AND not expired.
        The single source of truth for search visibility.

        Used in:
          - search_service.py: filter query
          - property_service.py: get_by_id guard
          - Celery listing_expiry: determines what to archive
        """
        return self.is_published and not self.is_expired

    @is_publicly_visible.expression
    def is_publicly_visible(cls):
        """SQL: WHERE Property.is_publicly_visible"""
        return sa.and_(
            cls.approval_status == ApprovalStatus.PUBLISHED,
            sa.or_(
                cls.expires_at.is_(None),
                cls.expires_at > func.now(),
            ),
        )

    # ── Computed properties: display-only ─────────────────────────────────────

    @property
    def days_until_expiry(self) -> Optional[int]:
        """Days remaining before this listing expires. None if no expiry set."""
        if self.expires_at is None:
            return None
        delta = self.expires_at - datetime.now(tz=timezone.utc)
        return max(0, delta.days)

    @property
    def public_address(self) -> str:
        """
        Decision 10: Returns full address OR city/state only, based on address_hidden.
        Callers must check if the requesting user has a confirmed booking before
        passing the full address.

        Use property_service.get_address_for_user(property, user) for the
        full gate check including booking verification.
        """
        if self.address_hidden:
            return f"{self.city}, {self.state}"
        parts = filter(None, [self.building_number, self.street, self.city, self.state])
        return ", ".join(parts)

    @property
    def primary_image(self) -> Optional[PropertyImage]:
        """Returns the primary image, or first image if none marked primary."""
        for img in self.images:
            if img.is_primary:
                return img
        return self.images[0] if self.images else None

    # ── repr ──────────────────────────────────────────────────────────────────

    def __repr__(self) -> str:
        return (
            f"<Property id={self.id} "
            f"title={self.title!r} "
            f"status={self.approval_status.value!r}>"
        )


# ─── PropertyFeature Model ──────────────────────────────────────────────────

class PropertyFeature(Base, UUIDMixin, CreatedAtMixin):
    """
    Dynamic amenity master list (Decision 7).

    Instead of boolean columns (is_furnished, has_gym, has_pool), amenities are
    rows in this table. Adding "Rooftop Terrace" = one INSERT, zero schema changes.

    Table: property_features
    Seed data: 18 features across 4 categories (see FeatureCategory docstring).

    The icon field stores an emoji or icon name for frontend rendering
    without hardcoding icons per feature in the UI.
    """

    __tablename__ = "property_features"

    name: Mapped[str] = mapped_column(
        String(100), nullable=False, unique=True,
        comment="e.g. 'Furnished', 'Swimming Pool', 'CCTV'. Must be unique.",
    )
    icon: Mapped[Optional[str]] = mapped_column(
        String(50), nullable=True,
        comment="Emoji or icon name for frontend display. e.g. '🏊' or 'swimming-pool'.",
    )
    category: Mapped[FeatureCategory] = mapped_column(
        _feature_category_col, nullable=False,
        index=True,
        comment="Groups features in UI: amenities | rules | building | security.",
    )

    # Many-to-many back to properties
    properties: Mapped[list[Property]] = relationship(
        "Property",
        secondary="property_feature_map",
        back_populates="features",
    )

    def __repr__(self) -> str:
        return (
            f"<PropertyFeature "
            f"name={self.name!r} "
            f"category={self.category.value!r}>"
        )


# ─── PropertyFeatureMap Model ────────────────────────────────────────────────

class PropertyFeatureMap(Base):
    """
    Junction table linking properties to their features.

    Composite PK (property_id, feature_id) — no surrogate UUID needed.
    ON DELETE CASCADE on property_id: deleting a property removes its feature links.

    Usage:
      property.features.append(feature)     # via relationship — SQLAlchemy handles INSERT
      "Gym" in [f.name for f in property.features]
    """

    __tablename__ = "property_feature_map"

    property_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("properties.id", ondelete="CASCADE"),
        primary_key=True,
        nullable=False,
    )
    feature_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("property_features.id", ondelete="RESTRICT"),
        primary_key=True,
        nullable=False,
    )

    def __repr__(self) -> str:
        return (
            f"<PropertyFeatureMap "
            f"property_id={self.property_id} "
            f"feature_id={self.feature_id}>"
        )
