"""payments: amount to BigInteger, add created_at

Revision ID: 7ad3459a721f
Revises: 24846aa0a675
Create Date: 2026-07-23 02:06:36.181573+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ad3459a721f'
down_revision: str | None = '24846aa0a675'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('payments', 'subscription_type',
               existing_type=sa.VARCHAR(length=50),
               comment="Intended plan: 'renter' or 'agent'. String, not FK or PostgreSQL enum. Validated by Pydantic at API boundary. The Subscription row is created after webhook confirms success.",
               existing_comment="Intended plan: 'renter' or 'agent'. String, not FK or PostgreSQL enum. Validated by Pydantic SubscriptionPlanType at API boundary. The Subscription row is created after webhook confirms success. No migration needed to add new plan types.",
               existing_nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.BigInteger(),
               comment='Amount in kobo (Paystack native unit). 100000 = ₦1,000.',
               existing_comment='Amount in kobo (Paystack uses kobo). e.g. 100000 = ₦1,000.',
               existing_nullable=False)
    op.alter_column('payments', 'provider',
               existing_type=sa.VARCHAR(length=50),
               comment="Payment gateway name. Currently always 'paystack'.",
               existing_comment="Payment gateway name. Currently always 'paystack'. Stored as string for flexibility.",
               existing_nullable=False,
               existing_server_default=sa.text("'paystack'::character varying"))
    op.alter_column('payments', 'paystack_reference',
               existing_type=sa.VARCHAR(length=255),
               comment='Paystack transaction reference. UNIQUE prevents duplicate webhook handling. Set when payment is initialized. Used to match inbound webhooks.',
               existing_comment="Paystack transaction reference (e.g. 'TXN_abc123xyz'). UNIQUE constraint prevents duplicate webhook handling. Set when payment is initialized. Used to match inbound webhooks.",
               existing_nullable=True)
    op.alter_column('payments', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Payment link/session expiry if applicable.',
               existing_comment='Not the subscription expiry — the payment link/session expiry if applicable.',
               existing_nullable=True)
    op.drop_index('idx_properties_location', table_name='properties', postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_properties_location', 'properties', [sa.text('st_setsrid(st_makepoint(longitude, latitude), 4326)')], unique=False, postgresql_using='gist')
    op.alter_column('payments', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Not the subscription expiry — the payment link/session expiry if applicable.',
               existing_comment='Payment link/session expiry if applicable.',
               existing_nullable=True)
    op.alter_column('payments', 'paystack_reference',
               existing_type=sa.VARCHAR(length=255),
               comment="Paystack transaction reference (e.g. 'TXN_abc123xyz'). UNIQUE constraint prevents duplicate webhook handling. Set when payment is initialized. Used to match inbound webhooks.",
               existing_comment='Paystack transaction reference. UNIQUE prevents duplicate webhook handling. Set when payment is initialized. Used to match inbound webhooks.',
               existing_nullable=True)
    op.alter_column('payments', 'provider',
               existing_type=sa.VARCHAR(length=50),
               comment="Payment gateway name. Currently always 'paystack'. Stored as string for flexibility.",
               existing_comment="Payment gateway name. Currently always 'paystack'.",
               existing_nullable=False,
               existing_server_default=sa.text("'paystack'::character varying"))
    op.alter_column('payments', 'amount',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=15, scale=2),
               comment='Amount in kobo (Paystack uses kobo). e.g. 100000 = ₦1,000.',
               existing_comment='Amount in kobo (Paystack native unit). 100000 = ₦1,000.',
               existing_nullable=False)
    op.alter_column('payments', 'subscription_type',
               existing_type=sa.VARCHAR(length=50),
               comment="Intended plan: 'renter' or 'agent'. String, not FK or PostgreSQL enum. Validated by Pydantic SubscriptionPlanType at API boundary. The Subscription row is created after webhook confirms success. No migration needed to add new plan types.",
               existing_comment="Intended plan: 'renter' or 'agent'. String, not FK or PostgreSQL enum. Validated by Pydantic at API boundary. The Subscription row is created after webhook confirms success.",
               existing_nullable=True)
    op.drop_column('payments', 'created_at')
    # ### end Alembic commands ###