"""initial_schema

Revision ID: 24846aa0a675
Revises:
Create Date: 2026-06-22 19:00:51.326766+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24846aa0a675"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ── Extensions (must exist before tables that use them) ──
    op.execute('CREATE EXTENSION IF NOT EXISTS "postgis"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # ── updated_at trigger function ──
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # ... all the auto-generated table creations, enums, indexes ...
    # (leave everything Alembic generated in the middle)

    op.create_table(
        "property_features",
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="e.g. 'Furnished', 'Swimming Pool', 'CCTV'. Must be unique.",
        ),
        sa.Column(
            "icon",
            sa.String(length=50),
            nullable=True,
            comment="Emoji or icon name for frontend display. e.g. '🏊' or 'swimming-pool'.",
        ),
        sa.Column(
            "category",
            sa.Enum("amenities", "rules", "building", "security", name="feature_category"),
            nullable=False,
            comment="Groups features in UI: amenities | rules | building | security.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_property_features_category"), "property_features", ["category"], unique=False
    )
    op.create_table(
        "users",
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="Stored lowercase. Unique across all user types.",
        ),
        sa.Column(
            "first_name",
            sa.String(length=100),
            nullable=False,
            comment="Overwritten by KYC provider on approval.",
        ),
        sa.Column(
            "last_name",
            sa.String(length=100),
            nullable=False,
            comment="Overwritten by KYC provider on approval.",
        ),
        sa.Column(
            "dob", sa.Date(), nullable=True, comment="Overwritten by KYC provider on approval."
        ),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("profile_image_url", sa.String(length=512), nullable=True),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=True,
            comment="NULL for OAuth-only users. Never store plaintext password.",
        ),
        sa.Column(
            "oauth_provider",
            sa.Enum("google", "apple", "facebook", name="oauth_provider"),
            nullable=True,
        ),
        sa.Column(
            "oauth_provider_id",
            sa.String(length=255),
            nullable=True,
            comment="The user's ID on the OAuth provider. Matches returning users.",
        ),
        sa.Column(
            "role",
            sa.Enum("renter", "agent", "admin", name="user_role"),
            server_default=sa.text("'renter'"),
            nullable=False,
        ),
        sa.Column(
            "admin_role",
            sa.Enum("super_admin", "admin", "moderator", name="admin_role"),
            nullable=True,
            comment="NULL for non-admin users. Subdivides admin access level.",
        ),
        sa.Column(
            "kyc_status",
            sa.Enum("not_submitted", "pending_review", "verified", "rejected", name="kyc_status"),
            server_default=sa.text("'not_submitted'"),
            nullable=False,
        ),
        sa.Column(
            "verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Admin-granted verified badge. Separate from KYC.",
        ),
        sa.Column("agency_name", sa.String(length=255), nullable=True),
        sa.Column("agent_bio", sa.Text(), nullable=True),
        sa.Column("license_number", sa.String(length=100), nullable=True),
        sa.Column("years_experience", sa.Integer(), nullable=True),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "suspension_reason",
            sa.String(length=500),
            nullable=True,
            comment="Required when suspending. Shown to the suspended user.",
        ),
        sa.Column("suspended_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["suspended_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "admin_audit_log",
        sa.Column(
            "admin_id",
            sa.UUID(),
            nullable=False,
            comment="The admin who performed this action. RESTRICT: audit logs are permanent — cannot delete admin with actions. Indexed: 'get all actions by admin X' queries.",
        ),
        sa.Column(
            "action",
            sa.String(length=100),
            nullable=False,
            comment="What the admin did. Valid values (validated in admin_service): approve_property | reject_property | suspend_property | suspend_user | unsuspend_user | override_kyc | resolve_report | dismiss_report | grant_subscription | change_role | verify_agent | approve_media | reject_media. Stored as String for flexibility — adding new actions requires no migration.",
        ),
        sa.Column(
            "target_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of entity affected. Valid values: user | property | report | kyc_document | subscription | media_asset. Drives polymorphic lookup. Validated in admin_service.",
        ),
        sa.Column(
            "target_id",
            sa.UUID(),
            nullable=False,
            comment="UUID of the entity affected. No DB-level FK — target table varies. Service resolves: if target_type='user' → user_service.get_by_id(id).",
        ),
        sa.Column(
            "details",
            sa.Text(),
            nullable=True,
            comment="Free-text description of the action and reasoning. Required for destructive actions (suspend, reject, override). Enforced in admin_service — not a DB constraint. e.g. 'Confirmed fake listing — stock photos from Lagos, property in Abuja.'",
        ),
        sa.Column(
            "previous_value",
            sa.String(length=255),
            nullable=True,
            comment="The value BEFORE the action. For tracking state transitions. e.g. action='change_role', previous_value='renter', new_value='agent'. NULL when not applicable (e.g. resolve_report).",
        ),
        sa.Column(
            "new_value",
            sa.String(length=255),
            nullable=True,
            comment="The value AFTER the action. For tracking state transitions. e.g. action='suspend_user', previous_value='active', new_value='suspended'. NULL when not applicable.",
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="Admin's IP address at the time of action. Security evidence for detecting compromised admin accounts. IPv6 max length = 45 chars. Stored ONLY here — not in analytics.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["admin_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_admin_action", "admin_audit_log", ["admin_id", "action"], unique=False
    )
    op.create_index(
        "idx_audit_target_type_created",
        "admin_audit_log",
        ["target_type", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_audit_log_admin_id"), "admin_audit_log", ["admin_id"], unique=False
    )
    op.create_table(
        "kyc_documents",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="The user who submitted this document. CASCADE: NDPR right to erasure — deleting user must delete ALL their identity data (government IDs, photos, personal details). Indexed: admin queries 'get all KYC docs for user X'.",
        ),
        sa.Column(
            "document_type",
            sa.Enum("national_id", "passport", "drivers_license", name="kyc_document_type"),
            nullable=False,
            comment="Type of identity document: national_id | passport | drivers_license.",
        ),
        sa.Column(
            "document_url",
            sa.String(length=512),
            nullable=False,
            comment="Object storage URL. Access-controlled — never publicly listable. Contains sensitive identity information.",
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", name="kyc_document_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
            comment="Provider verification status: pending | approved | rejected. Indexed: admin queries 'get all pending KYC documents'. NOT the user's overall kyc_status — use effective_status for that.",
        ),
        sa.Column(
            "rejection_reason",
            sa.String(length=500),
            nullable=True,
            comment="Set by provider (or admin via KycAdminReview) when status=rejected.",
        ),
        sa.Column(
            "provider",
            sa.String(length=50),
            nullable=True,
            comment="e.g. 'smile_identity', 'youverify'. NULL if not yet submitted.",
        ),
        sa.Column(
            "provider_reference",
            sa.String(length=255),
            nullable=True,
            comment="Provider's reference/transaction ID for this verification. NOT UNIQUE — providers may reuse references across resubmissions. Webhook handler finds the LATEST document: ORDER BY created_at DESC LIMIT 1. Indexed: webhook lookup needs to be fast.",
        ),
        sa.Column(
            "provider_response",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Full raw JSON response from the provider. Stored for audit and fraud investigation — never displayed directly to the user.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(document_url) > 0", name="chk_document_url"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kyc_documents_provider_reference"),
        "kyc_documents",
        ["provider_reference"],
        unique=False,
    )
    op.create_index(op.f("ix_kyc_documents_status"), "kyc_documents", ["status"], unique=False)
    op.create_index(op.f("ix_kyc_documents_user_id"), "kyc_documents", ["user_id"], unique=False)
    op.create_table(
        "media_assets",
        sa.Column(
            "uploaded_by",
            sa.UUID(),
            nullable=False,
            comment="Who uploaded this file. RESTRICT: cannot delete user who uploaded files (audit trail). Indexed: admin queries filter by uploader.",
        ),
        sa.Column(
            "original_url",
            sa.Text(),
            nullable=False,
            comment="URL of the original uploaded file (full resolution). Set on upload.",
        ),
        sa.Column(
            "optimized_url",
            sa.Text(),
            nullable=True,
            comment="URL of the compressed version. Set by Celery media_processing task after processing.",
        ),
        sa.Column(
            "thumbnail_url",
            sa.Text(),
            nullable=True,
            comment="URL of the small preview thumbnail. Set by Celery after processing.",
        ),
        sa.Column(
            "blurhash",
            sa.String(length=100),
            nullable=True,
            comment="Blurhash string for placeholder display while image loads. Generated by Celery from the original image. Frontend: <img src={thumbnail_url} placeholder={blurhash} />",
        ),
        sa.Column(
            "mime_type",
            sa.String(length=100),
            nullable=True,
            comment="MIME type (e.g. 'image/jpeg', 'image/png', 'video/mp4'). Detected on upload.",
        ),
        sa.Column(
            "file_size_kb",
            sa.Integer(),
            nullable=True,
            comment="File size in kilobytes. Set by Celery after processing.",
        ),
        sa.Column(
            "width",
            sa.Integer(),
            nullable=True,
            comment="Image/video width in pixels. Set by Celery after processing.",
        ),
        sa.Column(
            "height",
            sa.Integer(),
            nullable=True,
            comment="Image/video height in pixels. Set by Celery after processing.",
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "ready", "failed", name="media_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
            comment="Processing pipeline status. Celery transitions: pending → processing → ready (or failed). Indexed: Celery queries WHERE status='pending' to find work.",
        ),
        sa.Column(
            "moderation_status",
            sa.Enum("pending", "approved", "rejected", name="moderation_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
            comment="Content moderation status. Admin transitions: pending → approved (or rejected). Image is only visible when status=ready AND moderation_status=approved.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(width IS NULL AND height IS NULL) OR (width > 0 AND height > 0)",
            name="chk_dimensions",
        ),
        sa.CheckConstraint("file_size_kb IS NULL OR file_size_kb > 0", name="chk_file_size"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_media_assets_moderation_status"),
        "media_assets",
        ["moderation_status"],
        unique=False,
    )
    op.create_index(op.f("ix_media_assets_status"), "media_assets", ["status"], unique=False)
    op.create_index(
        op.f("ix_media_assets_uploaded_by"), "media_assets", ["uploaded_by"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="CASCADE: user deleted → their notifications are disposable. Indexed: notification feed queries filter by user_id.",
        ),
        sa.Column(
            "type",
            sa.String(length=50),
            nullable=False,
            comment="Notification type. Drives icon/color on frontend. Examples: booking_confirmed, property_approved, new_message, subscription_expiring, kyc_verified, report_resolved.",
        ),
        sa.Column(
            "message",
            sa.String(length=1000),
            nullable=False,
            comment="Human-readable notification text. Shown in notification feed.",
        ),
        sa.Column(
            "is_read",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="False = unread (bold on frontend). True = read. Toggled by PATCH /notifications/{id}/read. Indexed: 'unread count' queries filter by is_read=False.",
        ),
        sa.Column(
            "related_type",
            sa.String(length=50),
            nullable=True,
            comment="Deep-link target type. Combined with related_id, frontend navigates directly to the relevant entity. Valid values: booking | property | message | subscription | kyc | report. Validated in notification_service — not a PostgreSQL enum (flexible).",
        ),
        sa.Column(
            "related_id",
            sa.UUID(),
            nullable=True,
            comment="Deep-link target ID. Combined with related_type, frontend constructs the exact URL. Example: related_type='booking', related_id='abc-123' → frontend navigates to /bookings/abc-123.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False)
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "subscription_type",
            sa.String(length=50),
            nullable=True,
            comment="Intended plan: 'renter' or 'agent'. String, not FK or PostgreSQL enum. Validated by Pydantic SubscriptionPlanType at API boundary. The Subscription row is created after webhook confirms success. No migration needed to add new plan types.",
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
            comment="Amount in kobo (Paystack uses kobo). e.g. 100000 = ₦1,000.",
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "successful", "failed", "refunded", name="payment_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.String(length=50),
            server_default=sa.text("'paystack'"),
            nullable=False,
            comment="Payment gateway name. Currently always 'paystack'. Stored as string for flexibility.",
        ),
        sa.Column(
            "paystack_reference",
            sa.String(length=255),
            nullable=True,
            comment="Paystack transaction reference (e.g. 'TXN_abc123xyz'). UNIQUE constraint prevents duplicate webhook handling. Set when payment is initialized. Used to match inbound webhooks.",
        ),
        sa.Column(
            "paid_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set by webhook handler when Paystack confirms payment received.",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Not the subscription expiry — the payment link/session expiry if applicable.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="chk_payment_amount"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payments_paystack_reference"), "payments", ["paystack_reference"], unique=True
    )
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "properties",
        sa.Column(
            "owner_id", sa.UUID(), nullable=False, comment="The agent who created this listing."
        ),
        sa.Column(
            "rented_by_user_id",
            sa.UUID(),
            nullable=True,
            comment="Set when property is rented through the platform. NULL for offline rentals.",
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "price",
            sa.Numeric(precision=15, scale=2),
            nullable=False,
            comment="Always positive — enforced by chk_price CHECK constraint.",
        ),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
        sa.Column(
            "property_type",
            sa.Enum(
                "apartment",
                "house",
                "duplex",
                "studio",
                "commercial",
                "office",
                name="property_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("rent", "sale", "short_let", "lease", name="listing_status"),
            nullable=False,
            comment="What the agent is offering: rent, sale, short_let, lease.",
        ),
        sa.Column(
            "approval_status",
            sa.Enum(
                "draft",
                "pending_review",
                "approved",
                "rejected",
                "published",
                "reserved",
                "rented",
                "sold",
                "archived",
                "suspended",
                name="approval_status",
            ),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column(
            "rejection_reason",
            sa.String(length=500),
            nullable=True,
            comment="Set by admin when rejecting. Required when approval_status=rejected.",
        ),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column(
            "rented_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Stamped when agent marks property as rented.",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set to now() + 30 days when published (Decision 4). Celery listing_expiry job archives when this passes.",
        ),
        sa.Column("street", sa.String(length=300), nullable=True),
        sa.Column("building_number", sa.String(length=50), nullable=True),
        sa.Column(
            "formatted_address",
            sa.String(length=512),
            nullable=True,
            comment="Cached from Google Geocoding API. Not fetched on every request.",
        ),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(),
            nullable=False,
            comment="Used for PostGIS radius search and Google Places API nearby lookup.",
        ),
        sa.Column("longitude", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column(
            "address_hidden",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="When True, only city/state shown publicly (Decision 10). Full address revealed only to users with a confirmed booking.",
        ),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("bathrooms", sa.Integer(), nullable=True),
        sa.Column("master_bedrooms", sa.Integer(), nullable=True),
        sa.Column("toilets", sa.Integer(), nullable=True),
        sa.Column(
            "area_size",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Floor area in square metres.",
        ),
        sa.Column(
            "featured",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Admin-set. Featured listings appear in promoted slots.",
        ),
        sa.Column(
            "verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Admin-set. Shows a verified badge on the listing.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("area_size IS NULL OR area_size > 0", name="chk_area_size"),
        sa.CheckConstraint("bathrooms IS NULL OR bathrooms >= 0", name="chk_bathrooms"),
        sa.CheckConstraint("bedrooms IS NULL OR bedrooms >= 0", name="chk_bedrooms"),
        sa.CheckConstraint("latitude >= -90 AND latitude <= 90", name="chk_latitude"),
        sa.CheckConstraint("longitude >= -180 AND longitude <= 180", name="chk_longitude"),
        sa.CheckConstraint(
            "master_bedrooms IS NULL OR master_bedrooms >= 0", name="chk_master_bedrooms"
        ),
        sa.CheckConstraint("price > 0", name="chk_price"),
        sa.CheckConstraint("toilets IS NULL OR toilets >= 0", name="chk_toilets"),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["rented_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_properties_approval_status"), "properties", ["approval_status"], unique=False
    )
    op.create_index(op.f("ix_properties_city"), "properties", ["city"], unique=False)
    op.create_index(op.f("ix_properties_expires_at"), "properties", ["expires_at"], unique=False)
    op.create_index(op.f("ix_properties_owner_id"), "properties", ["owner_id"], unique=False)
    op.create_index(op.f("ix_properties_state"), "properties", ["state"], unique=False)
    op.create_table(
        "reports",
        sa.Column(
            "reporter_id",
            sa.UUID(),
            nullable=True,
            comment="The user who filed this report. SET NULL: user deleted → report survives, display as 'Deleted Account'. Indexed: admin queries 'get all reports by user X'. Not shown to the reported entity — reporter identity is admin-only.",
        ),
        sa.Column(
            "target_type",
            sa.Enum("property", "user", "message", "review", name="report_target_type"),
            nullable=False,
            comment="Type of entity being reported: property | user | message | review. Drives polymorphic lookup in service layer.",
        ),
        sa.Column(
            "target_id",
            sa.UUID(),
            nullable=False,
            comment="Polymorphic FK — references properties.id, users.id, messages.id, or reviews.id depending on target_type. No DB-level FK constraint (target table varies).",
        ),
        sa.Column(
            "reason",
            sa.Enum(
                "fake_listing",
                "scam",
                "inappropriate_content",
                "harassment",
                "wrong_information",
                "other",
                name="report_reason",
            ),
            nullable=False,
            comment="Report reason from standard moderation categories.",
        ),
        sa.Column(
            "details",
            sa.Text(),
            nullable=True,
            comment="Free-text description provided by the reporter.",
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "reviewed", "resolved", "dismissed", name="report_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
            comment="Report lifecycle status. Indexed: admin queries 'get all pending reports'.",
        ),
        sa.Column(
            "reviewed_by",
            sa.UUID(),
            nullable=True,
            comment="Admin who first reviewed this report. SET NULL: admin deleted → report survives. Indexed: 'get all reports reviewed by admin X' queries.",
        ),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set once, on first review. Does not change on later updates. Distinct from updated_at which tracks ANY change.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reviewed_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_reports_target_status", "reports", ["target_type", "status"], unique=False)
    op.create_index(op.f("ix_reports_reporter_id"), "reports", ["reporter_id"], unique=False)
    op.create_index(op.f("ix_reports_reviewed_by"), "reports", ["reviewed_by"], unique=False)
    op.create_index(op.f("ix_reports_status"), "reports", ["status"], unique=False)
    op.create_index(op.f("ix_reports_target_id"), "reports", ["target_id"], unique=False)
    op.create_index(op.f("ix_reports_target_type"), "reports", ["target_type"], unique=False)
    op.create_table(
        "saved_searches",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="The user who saved this search. CASCADE: user deleted → their saved searches are disposable. Indexed: 'get all saved searches for user X' queries.",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=True,
            comment="User-given name for this saved search. e.g. 'Lekki 3-bed under 500k', 'VI apartments'. NULL if user didn't name it. Shown in the saved searches list.",
        ),
        sa.Column(
            "city", sa.String(length=100), nullable=True, comment="Filter by city. NULL = any city."
        ),
        sa.Column(
            "state",
            sa.String(length=100),
            nullable=True,
            comment="Filter by state. NULL = any state.",
        ),
        sa.Column(
            "min_price",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
            comment="Minimum price filter. NULL = no minimum.",
        ),
        sa.Column(
            "max_price",
            sa.Numeric(precision=15, scale=2),
            nullable=True,
            comment="Maximum price filter. NULL = no maximum.",
        ),
        sa.Column(
            "property_type",
            sa.Enum(
                "apartment",
                "house",
                "duplex",
                "studio",
                "commercial",
                "office",
                name="property_type",
            ),
            nullable=True,
            comment="Filter by property type. NULL = any type.",
        ),
        sa.Column(
            "min_bedrooms",
            sa.Integer(),
            nullable=True,
            comment="Minimum number of bedrooms. NULL = any.",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="True = Celery checks this search for new matches. False = user paused alerts. Celery skips inactive searches. Indexed: Celery queries WHERE is_active=True.",
        ),
        sa.Column(
            "last_notified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the last alert notification was sent. NULL = never notified (alert everything matching since creation). Celery updates this after sending an alert. Used as the lower bound for 'new matches' query: WHERE property.created_at > saved_search.last_notified_at.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(min_price IS NULL OR max_price IS NULL) OR (max_price >= min_price)",
            name="chk_saved_search_price_range",
        ),
        sa.CheckConstraint(
            "max_price IS NULL OR max_price >= 0", name="chk_saved_search_max_price"
        ),
        sa.CheckConstraint(
            "min_bedrooms IS NULL OR min_bedrooms >= 0", name="chk_saved_search_bedrooms"
        ),
        sa.CheckConstraint(
            "min_price IS NULL OR min_price >= 0", name="chk_saved_search_min_price"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_saved_searches_is_active"), "saved_searches", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_saved_searches_last_notified_at"),
        "saved_searches",
        ["last_notified_at"],
        unique=False,
    )
    op.create_index(op.f("ix_saved_searches_user_id"), "saved_searches", ["user_id"], unique=False)
    op.create_table(
        "user_consent_log",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="The user who performed this consent action. CASCADE: right to erasure — consent logs contain IP addresses (personal data) that must be deleted with the user. Indexed: 'get consent history for user X' queries.",
        ),
        sa.Column(
            "consent_type",
            sa.String(length=50),
            nullable=False,
            comment="What the user consented to. Valid values (validated in consent_service): terms_of_service | privacy_policy | data_processing | marketing_email | marketing_sms | cookie_policy. Stored as String for flexibility — adding new types requires no migration.",
        ),
        sa.Column(
            "consented",
            sa.Boolean(),
            nullable=False,
            comment="True = user GAVE consent. False = user WITHDREW consent. The latest row per (user_id, consent_type) determines current status.",
        ),
        sa.Column(
            "consent_version",
            sa.String(length=50),
            nullable=True,
            comment="Version of the legal document the user consented to. e.g. '2.1', '3.0'. Required for terms_of_service and privacy_policy. When terms change, users must re-consent. This field proves which version they actually agreed to. Legally critical.",
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="IP address at the time of consent. IPv6 max length = 45 chars. Stored as NDPR legal evidence — proves the consent action came from the user's device. NOT stored in analytics (privacy-first), but IS stored here (legal requirement).",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=500),
            nullable=True,
            comment="Browser/device user agent at the time of consent. Additional evidence for NDPR compliance. e.g. 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0...)'",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_consent_log_user_id"), "user_consent_log", ["user_id"], unique=False
    )
    op.create_table(
        "user_notification_settings",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="One settings row per user. UNIQUE enforces 1:1. CASCADE: user deleted → their settings are disposable.",
        ),
        sa.Column(
            "email_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Master switch for email notifications. If False, no emails sent.",
        ),
        sa.Column(
            "push_enabled",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Master switch for push notifications (FCM). If False, no pushes sent.",
        ),
        sa.Column(
            "sms_enabled",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Master switch for SMS notifications. Default False (SMS costs money). Only enabled for critical alerts (e.g. payment confirmation).",
        ),
        sa.Column(
            "notify_new_message",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="New message received in a conversation.",
        ),
        sa.Column(
            "notify_booking_update",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Booking confirmed, rejected, or completed.",
        ),
        sa.Column(
            "notify_listing_approved",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Property listing approved or rejected by admin.",
        ),
        sa.Column(
            "notify_saved_search",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="New property matches a saved search alert.",
        ),
        sa.Column(
            "notify_listing_expiry",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Listing is about to expire (7-day warning).",
        ),
        sa.Column(
            "notify_subscription",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Subscription expiring soon (3-day warning) or expired.",
        ),
        sa.Column(
            "marketing_email",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Marketing emails. Default False (opt-in). NDPR compliance.",
        ),
        sa.Column(
            "marketing_sms",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Marketing SMS. Default False (opt-in). NDPR compliance.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "agent_availability",
        sa.Column(
            "agent_id",
            sa.UUID(),
            nullable=False,
            comment="The agent who owns this slot. RESTRICT: cannot delete agent with upcoming slots.",
        ),
        sa.Column(
            "property_id",
            sa.UUID(),
            nullable=False,
            comment="CASCADE: property deleted → its availability slots are meaningless.",
        ),
        sa.Column(
            "slot_start",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Start of the available window (timezone-aware).",
        ),
        sa.Column(
            "slot_end",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="End of the available window. Must be after slot_start.",
        ),
        sa.Column(
            "is_booked",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="False = slot is open. True = a confirmed booking holds this slot. updated_at timestamps exactly when this flips. booking_service checks is_booked=False before allowing a booking.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("slot_end > slot_start", name="chk_slot_order"),
        sa.ForeignKeyConstraint(["agent_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_availability_agent_id"), "agent_availability", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_availability_is_booked"), "agent_availability", ["is_booked"], unique=False
    )
    op.create_index(
        op.f("ix_agent_availability_property_id"),
        "agent_availability",
        ["property_id"],
        unique=False,
    )
    op.create_table(
        "bookings",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="The renter making the booking."),
        sa.Column(
            "payment_id",
            sa.UUID(),
            nullable=True,
            comment="Nullable because bookings are free (Decision 6). Only an active subscription is required. Retained for possible future paid priority-booking feature.",
        ),
        sa.Column(
            "visit_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="The agreed visit time. Must match an AgentAvailability slot.",
        ),
        sa.Column(
            "booking_type",
            sa.Enum("physical_inspection", "virtual", name="booking_type"),
            nullable=False,
            comment="physical_inspection (in-person) or virtual (video/360° tour).",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "confirmed", "rejected", "cancelled", "completed", name="booking_status"
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "rejection_reason",
            sa.String(length=500),
            nullable=True,
            comment="Required when status = rejected (Rule 7). Enforced by booking_service.reject() — not a DB constraint. Shown to the renter so they understand why the booking was declined.",
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
            comment="Optional message from the renter to the agent when booking.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bookings_property_id"), "bookings", ["property_id"], unique=False)
    op.create_index(op.f("ix_bookings_status"), "bookings", ["status"], unique=False)
    op.create_index(op.f("ix_bookings_user_id"), "bookings", ["user_id"], unique=False)
    op.create_index(op.f("ix_bookings_visit_time"), "bookings", ["visit_time"], unique=False)
    op.create_table(
        "conversations",
        sa.Column(
            "property_id",
            sa.UUID(),
            nullable=True,
            comment="The property this conversation is about. SET NULL: property deleted → conversation survives (messages are permanent). NULL for support conversations or admin-initiated threads.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "favorites",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="The user who bookmarked this property. CASCADE: user deleted → favorites are disposable. Indexed: 'get all favorites for user X' queries (most common).",
        ),
        sa.Column(
            "property_id",
            sa.UUID(),
            nullable=False,
            comment="The bookmarked property. CASCADE: property deleted → favorite link is meaningless. Indexed: 'get all users who favorited property X' queries. Part of UNIQUE constraint (user_id, property_id).",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "property_id", name="uq_user_favorite"),
    )
    op.create_index(op.f("ix_favorites_property_id"), "favorites", ["property_id"], unique=False)
    op.create_index(op.f("ix_favorites_user_id"), "favorites", ["user_id"], unique=False)
    op.create_table(
        "kyc_admin_reviews",
        sa.Column(
            "kyc_document_id",
            sa.UUID(),
            nullable=False,
            comment="The KYC document being reviewed. CASCADE: document deleted → its reviews are meaningless. Indexed: 'get all reviews for document X' queries.",
        ),
        sa.Column(
            "admin_id",
            sa.UUID(),
            nullable=False,
            comment="The admin who made this decision. RESTRICT: cannot delete admin who made override decisions (audit trail). Indexed: 'get all decisions by admin X' queries.",
        ),
        sa.Column(
            "decision",
            sa.Enum("approved", "rejected", name="kyc_review_decision"),
            nullable=False,
            comment="Admin's decision: approved | rejected. Always final (Rule 8).",
        ),
        sa.Column(
            "reason",
            sa.String(length=500),
            nullable=False,
            comment="Required for ALL decisions. Why the admin is overriding (or confirming) the provider result. Shown to the user in the notification. e.g. 'User provided additional evidence via video call, ref #1234'",
        ),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Optional free-form supporting evidence. e.g. { 'suspicion': 'photo_mismatch', 'notes': 'Face does not match', 'reference': '#1234' }. Stored for audit trail and dispute resolution.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["admin_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["kyc_document_id"], ["kyc_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_kyc_admin_reviews_admin_id"), "kyc_admin_reviews", ["admin_id"], unique=False
    )
    op.create_index(
        op.f("ix_kyc_admin_reviews_kyc_document_id"),
        "kyc_admin_reviews",
        ["kyc_document_id"],
        unique=False,
    )
    op.create_table(
        "property_analytics",
        sa.Column(
            "property_id",
            sa.UUID(),
            nullable=False,
            comment="The property this event is about. CASCADE: property deleted → its analytics are disposable. Indexed: almost every query filters by property_id. Part of composite index (property_id, created_at) for dashboard queries.",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=True,
            comment="The user who triggered this event. NULL for anonymous guests. SET NULL: user deleted → analytics survive for aggregation. Indexed: 'get all activity by user X' queries.",
        ),
        sa.Column(
            "event_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of interaction. Valid values (validated in analytics_service): view | contact | booking | favorite | phone_reveal | share | search_impression. Stored as String (not enum) for flexibility — adding new types requires no migration.",
        ),
        sa.Column(
            "session_id",
            sa.String(length=100),
            nullable=True,
            comment="Frontend session identifier for guest activity tracking. Generated by frontend (localStorage UUID or cookie). NULL if session tracking unavailable. Allows grouping guest events into sessions for funnel analysis. Not PII — random identifier, not tied to personal data.",
        ),
        sa.Column(
            "event_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Flexible context data. Structure varies by event_type: view:            {'referrer': 'search_results', 'position': 5, 'device': 'mobile'} contact:         {'method': 'message', 'search_query': 'lekki 3 bed'} share:           {'platform': 'whatsapp'} search_impression: {'search_query': '...', 'page': 2, 'position': 15} Queryable: WHERE event_metadata->>'referrer' = 'search_results'.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_analytics_property_created",
        "property_analytics",
        ["property_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_analytics_property_id"),
        "property_analytics",
        ["property_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_analytics_user_id"), "property_analytics", ["user_id"], unique=False
    )
    op.create_table(
        "property_feature_map",
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["feature_id"], ["property_features.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("property_id", "feature_id"),
    )
    op.create_table(
        "property_images",
        sa.Column(
            "property_id",
            sa.UUID(),
            nullable=False,
            comment="Which property this image belongs to. CASCADE: property deleted → image links are meaningless. Indexed: 'get all images for property X' queries.",
        ),
        sa.Column(
            "media_asset_id",
            sa.UUID(),
            nullable=False,
            comment="The media asset (file) this image references. RESTRICT: cannot delete media asset while it's linked to a property. Delete the PropertyImage first, then the MediaAsset.",
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Display position. 0 = first (hero image). Lower numbers appear first.",
        ),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="The hero image for this property. Shown in search results and cards. Exactly one per property (enforced in service layer).",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["media_asset_id"], ["media_assets.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_property_images_media_asset_id"),
        "property_images",
        ["media_asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_property_images_property_id"), "property_images", ["property_id"], unique=False
    )
    op.create_table(
        "search_history",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=True,
            comment="The user who performed this search. NULL for anonymous guests. SET NULL: user deleted → search history survives for analytics. Indexed: 'get search history for user X' queries.",
        ),
        sa.Column(
            "location",
            sa.String(length=300),
            nullable=True,
            comment="The location string the user searched for. e.g. 'Lekki Phase 1', 'Victoria Island', 'Ikoyi'. Stored as entered by user. Normalized for analytics in a future task.",
        ),
        sa.Column(
            "property_id",
            sa.UUID(),
            nullable=True,
            comment="The property the user clicked from search results. NULL for the search query itself (no click yet). SET NULL: property deleted → search history survives. Used for search-to-click conversion analytics.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_search_history_user_id"), "search_history", ["user_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "payment_id",
            sa.UUID(),
            nullable=True,
            comment="The payment that created this subscription period. Nullable: admin may grant free subscriptions (testing, promotions). When NULL, free_reason must be provided (enforced in service).",
        ),
        sa.Column(
            "plan_type",
            sa.Enum("renter", "agent", name="subscription_plan"),
            nullable=False,
            comment="renter (₦1,000/mo) or agent (₦10,000/mo).",
        ),
        sa.Column(
            "status",
            sa.Enum("active", "expired", "cancelled", name="subscription_status"),
            server_default=sa.text("'active'"),
            nullable=False,
            comment="Updated by Celery subscription_check task (runs hourly). Do NOT use this alone to check access — use is_active hybrid_property which also validates expires_at > now().",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this subscription period began (= payment confirmed at).",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this period ends (= started_at + 30 days). Celery checks this hourly to send warnings and expire subscriptions.",
        ),
        sa.Column(
            "cancelled_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Set when user cancels. Access continues until expires_at.",
        ),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "free_reason",
            sa.Text(),
            nullable=True,
            comment="Required when payment_id IS NULL. Explains why this subscription was granted without payment. e.g. 'Admin promotional grant', 'Testing account', 'Compensation for downtime'. Enforced in service layer, not DB constraint.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cancelled_at IS NULL OR cancelled_at >= started_at", name="chk_cancellation_date"
        ),
        sa.CheckConstraint("expires_at > started_at", name="chk_subscription_dates"),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_expires_at"), "subscriptions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False)
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "virtual_tours",
        sa.Column(
            "property_id",
            sa.UUID(),
            nullable=False,
            comment="Which property this tour belongs to. CASCADE: property deleted → tour links are meaningless.",
        ),
        sa.Column(
            "url",
            sa.Text(),
            nullable=False,
            comment="Full URL to the external tour (e.g. 'https://my.matterport.com/show/?m=...').",
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="Display position. Most properties have at most one tour.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(url) > 0", name="chk_tour_url"),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_reviews",
        sa.Column(
            "agent_id",
            sa.UUID(),
            nullable=False,
            comment="The agent being reviewed. RESTRICT: reviews are permanent records. Indexed: 'get all reviews for agent X' queries (most common — shown on agent profile).",
        ),
        sa.Column(
            "reviewer_id",
            sa.UUID(),
            nullable=False,
            comment="The renter who wrote this review. Named reviewer_id (not user_id) to avoid ambiguity with Review.user_id. Both refer to the renter. Part of UNIQUE constraint (reviewer_id, booking_id) — one review per booking.",
        ),
        sa.Column(
            "booking_id",
            sa.UUID(),
            nullable=False,
            comment="The completed booking that enabled this review. RESTRICT: reviews are permanent records. Part of UNIQUE constraint (reviewer_id, booking_id) — one review per booking.",
        ),
        sa.Column(
            "rating",
            sa.Integer(),
            nullable=False,
            comment="Star rating from 1 to 5. Integer only — no half-stars. Enforced by chk_agent_review_rating CHECK constraint.",
        ),
        sa.Column(
            "body",
            sa.Text(),
            nullable=True,
            comment="Written review text. Optional — user may submit rating only.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("agent_id <> reviewer_id", name="chk_agent_not_self_review"),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name="chk_agent_review_rating"),
        sa.ForeignKeyConstraint(["agent_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reviewer_id", "booking_id", name="uq_agent_review_per_booking"),
    )
    op.create_index(op.f("ix_agent_reviews_agent_id"), "agent_reviews", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_agent_reviews_booking_id"), "agent_reviews", ["booking_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_reviews_reviewer_id"), "agent_reviews", ["reviewer_id"], unique=False
    )
    op.create_table(
        "conversation_participants",
        sa.Column(
            "conversation_id",
            sa.UUID(),
            nullable=False,
            comment="CASCADE: conversation deleted → participant links are meaningless.",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Indexed separately from PK for 'find all conversations for user X' queries. RESTRICT: cannot delete user while they're a participant in conversations.",
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this user joined the conversation.",
        ),
        sa.Column(
            "last_read_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the user last opened this conversation. NULL = never opened (all messages are unread). Updated by messaging_service.mark_as_read(). Used to calculate unread message count.",
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("conversation_id", "user_id"),
    )
    op.create_index(
        op.f("ix_conversation_participants_user_id"),
        "conversation_participants",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column(
            "conversation_id",
            sa.UUID(),
            nullable=False,
            comment="Which conversation this message belongs to. Indexed: every message list query filters by conversation_id. CASCADE: conversation deleted → its messages are deleted too.",
        ),
        sa.Column(
            "sender_id",
            sa.UUID(),
            nullable=False,
            comment="Who sent this message. RESTRICT: cannot delete user who sent messages (preserves message integrity). Suspended users' messages remain visible — they just can't send new ones.",
        ),
        sa.Column(
            "body",
            sa.Text(),
            nullable=False,
            comment="Message content. Max 5000 characters (enforced by chk_message_length).",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(body) > 0 AND length(body) <= 5000", name="chk_message_length"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_messages_sender_id"), "messages", ["sender_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="The renter who wrote this review. RESTRICT: reviews are permanent records — cannot delete user who wrote them. Indexed: 'get all reviews by user X' queries.",
        ),
        sa.Column(
            "property_id",
            sa.UUID(),
            nullable=False,
            comment="The property being reviewed. RESTRICT: reviews are permanent records. Indexed: 'get all reviews for property X' queries (most common).",
        ),
        sa.Column(
            "booking_id",
            sa.UUID(),
            nullable=False,
            comment="The completed booking that enabled this review. RESTRICT: reviews are permanent records. Part of UNIQUE constraint (user_id, booking_id) — one review per booking.",
        ),
        sa.Column(
            "rating",
            sa.Integer(),
            nullable=False,
            comment="Star rating from 1 to 5. Integer only — no half-stars. Enforced by chk_review_rating CHECK constraint.",
        ),
        sa.Column(
            "body",
            sa.Text(),
            nullable=True,
            comment="Written review text. Optional — user may submit rating only.",
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating >= 1 AND rating <= 5", name="chk_review_rating"),
        sa.ForeignKeyConstraint(["booking_id"], ["bookings.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "booking_id", name="uq_review_per_booking"),
    )
    op.create_index(op.f("ix_reviews_booking_id"), "reviews", ["booking_id"], unique=False)
    op.create_index(op.f("ix_reviews_property_id"), "reviews", ["property_id"], unique=False)
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    # ### end Alembic commands ###
    # ... end of auto-generated code ...

    # ── PostGIS spatial index (cannot be autogenerated by Alembic) ──
    op.execute("""
        CREATE INDEX idx_properties_location ON properties
        USING GiST (ST_SetSRID(ST_MakePoint(longitude, latitude), 4326))
    """)

    # ── updated_at triggers on TimestampMixin tables ──
    # These tables have an updated_at column (from TimestampMixin).
    # Tables with only CreatedAtMixin are skipped.
    _tables_with_updated_at = [
        "users",
        "properties",
        "payments",
        "subscriptions",
        "agent_availability",
        "bookings",
        "media_assets",
        "kyc_documents",
        "user_notification_settings",
        "reports",
    ]
    for table_name in _tables_with_updated_at:
        op.execute(f"""
            CREATE TRIGGER set_updated_at
                BEFORE UPDATE ON {table_name}
                FOR EACH ROW
                EXECUTE FUNCTION update_updated_at_column();
        """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ── Drop triggers first ──
    _tables_with_updated_at = [
        "users",
        "properties",
        "payments",
        "subscriptions",
        "agent_availability",
        "bookings",
        "media_assets",
        "kyc_documents",
        "user_notification_settings",
        "reports",
    ]
    for table_name in _tables_with_updated_at:
        op.execute(f"DROP TRIGGER IF EXISTS set_updated_at ON {table_name}")

    # ── Drop trigger function ──
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column()")

    # ── Drop PostGIS spatial index ──
    op.execute("DROP INDEX IF EXISTS idx_properties_location")

    # ... all the auto-generated table drops, enum drops ...
    # (leave everything Alembic generated in the middle)
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_property_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_booking_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_messages_sender_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        op.f("ix_conversation_participants_user_id"), table_name="conversation_participants"
    )
    op.drop_table("conversation_participants")
    op.drop_index(op.f("ix_agent_reviews_reviewer_id"), table_name="agent_reviews")
    op.drop_index(op.f("ix_agent_reviews_booking_id"), table_name="agent_reviews")
    op.drop_index(op.f("ix_agent_reviews_agent_id"), table_name="agent_reviews")
    op.drop_table("agent_reviews")
    op.drop_table("virtual_tours")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_expires_at"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_search_history_user_id"), table_name="search_history")
    op.drop_table("search_history")
    op.drop_index(op.f("ix_property_images_property_id"), table_name="property_images")
    op.drop_index(op.f("ix_property_images_media_asset_id"), table_name="property_images")
    op.drop_table("property_images")
    op.drop_table("property_feature_map")
    op.drop_index(op.f("ix_property_analytics_user_id"), table_name="property_analytics")
    op.drop_index(op.f("ix_property_analytics_property_id"), table_name="property_analytics")
    op.drop_index("idx_analytics_property_created", table_name="property_analytics")
    op.drop_table("property_analytics")
    op.drop_index(op.f("ix_kyc_admin_reviews_kyc_document_id"), table_name="kyc_admin_reviews")
    op.drop_index(op.f("ix_kyc_admin_reviews_admin_id"), table_name="kyc_admin_reviews")
    op.drop_table("kyc_admin_reviews")
    op.drop_index(op.f("ix_favorites_user_id"), table_name="favorites")
    op.drop_index(op.f("ix_favorites_property_id"), table_name="favorites")
    op.drop_table("favorites")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_bookings_visit_time"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_user_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_status"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_property_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_agent_availability_property_id"), table_name="agent_availability")
    op.drop_index(op.f("ix_agent_availability_is_booked"), table_name="agent_availability")
    op.drop_index(op.f("ix_agent_availability_agent_id"), table_name="agent_availability")
    op.drop_table("agent_availability")
    op.drop_table("user_notification_settings")
    op.drop_index(op.f("ix_user_consent_log_user_id"), table_name="user_consent_log")
    op.drop_table("user_consent_log")
    op.drop_index(op.f("ix_saved_searches_user_id"), table_name="saved_searches")
    op.drop_index(op.f("ix_saved_searches_last_notified_at"), table_name="saved_searches")
    op.drop_index(op.f("ix_saved_searches_is_active"), table_name="saved_searches")
    op.drop_table("saved_searches")
    op.drop_index(op.f("ix_reports_target_type"), table_name="reports")
    op.drop_index(op.f("ix_reports_target_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_status"), table_name="reports")
    op.drop_index(op.f("ix_reports_reviewed_by"), table_name="reports")
    op.drop_index(op.f("ix_reports_reporter_id"), table_name="reports")
    op.drop_index("idx_reports_target_status", table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_properties_state"), table_name="properties")
    op.drop_index(op.f("ix_properties_owner_id"), table_name="properties")
    op.drop_index(op.f("ix_properties_expires_at"), table_name="properties")
    op.drop_index(op.f("ix_properties_city"), table_name="properties")
    op.drop_index(op.f("ix_properties_approval_status"), table_name="properties")
    op.drop_table("properties")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_paystack_reference"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_media_assets_uploaded_by"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_status"), table_name="media_assets")
    op.drop_index(op.f("ix_media_assets_moderation_status"), table_name="media_assets")
    op.drop_table("media_assets")
    op.drop_index(op.f("ix_kyc_documents_user_id"), table_name="kyc_documents")
    op.drop_index(op.f("ix_kyc_documents_status"), table_name="kyc_documents")
    op.drop_index(op.f("ix_kyc_documents_provider_reference"), table_name="kyc_documents")
    op.drop_table("kyc_documents")
    op.drop_index(op.f("ix_admin_audit_log_admin_id"), table_name="admin_audit_log")
    op.drop_index("idx_audit_target_type_created", table_name="admin_audit_log")
    op.drop_index("idx_audit_admin_action", table_name="admin_audit_log")
    op.drop_table("admin_audit_log")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_property_features_category"), table_name="property_features")
    op.drop_table("property_features")
    # ### end Alembic commands ###
    # ... end of auto-generated code ...

    # ── Extensions (leave installed — other databases may use them) ──
    # Typically you don't DROP extensions in downgrade.
    # If you really want to:
    # op.execute('DROP EXTENSION IF EXISTS "postgis"')
    # op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')
