"""messaging: conversations, participants, messages

Revision ID: 4b7953f3a0f5
Revises: 7ad3459a721f
Create Date: 2026-07-24 05:03:54.755796+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b7953f3a0f5"
down_revision: str | None = "7ad3459a721f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversation_participants",
        "conversation_id",
        existing_type=sa.UUID(),
        comment="CASCADE: conversation deleted → participant links are removed.",
        existing_comment="CASCADE: conversation deleted → participant links are meaningless.",
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_participants",
        "user_id",
        existing_type=sa.UUID(),
        comment="RESTRICT: cannot delete user who is in active conversations.",
        existing_comment="Indexed separately from PK for 'find all conversations for user X' queries. RESTRICT: cannot delete user while they're a participant in conversations.",
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_participants",
        "last_read_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the user last opened this conversation. NULL = never opened (all messages are unread).",
        existing_comment="When the user last opened this conversation. NULL = never opened (all messages are unread). Updated by messaging_service.mark_as_read(). Used to calculate unread message count.",
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "property_id",
        existing_type=sa.UUID(),
        comment="The property this conversation is about. SET NULL: property deleted → conversation survives. NULL for support conversations or admin-initiated threads.",
        existing_comment="The property this conversation is about. SET NULL: property deleted → conversation survives (messages are permanent). NULL for support conversations or admin-initiated threads.",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_conversations_property_id"), "conversations", ["property_id"], unique=False
    )
    op.alter_column(
        "messages",
        "conversation_id",
        existing_type=sa.UUID(),
        comment="Which conversation this message belongs to.",
        existing_comment="Which conversation this message belongs to. Indexed: every message list query filters by conversation_id. CASCADE: conversation deleted → its messages are deleted too.",
        existing_nullable=False,
    )
    op.alter_column(
        "messages",
        "sender_id",
        existing_type=sa.UUID(),
        comment="Who sent this message.",
        existing_comment="Who sent this message. RESTRICT: cannot delete user who sent messages (preserves message integrity). Suspended users' messages remain visible — they just can't send new ones.",
        existing_nullable=False,
    )
    op.alter_column(
        "messages",
        "body",
        existing_type=sa.TEXT(),
        comment="Message content. Max 5000 characters.",
        existing_comment="Message content. Max 5000 characters (enforced by chk_message_length).",
        existing_nullable=False,
    )
    op.create_index(
        "ix_messages_conversation_created_at",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_conversation_created_at", table_name="messages")
    op.alter_column(
        "messages",
        "body",
        existing_type=sa.TEXT(),
        comment="Message content. Max 5000 characters (enforced by chk_message_length).",
        existing_comment="Message content. Max 5000 characters.",
        existing_nullable=False,
    )
    op.alter_column(
        "messages",
        "sender_id",
        existing_type=sa.UUID(),
        comment="Who sent this message. RESTRICT: cannot delete user who sent messages (preserves message integrity). Suspended users' messages remain visible — they just can't send new ones.",
        existing_comment="Who sent this message.",
        existing_nullable=False,
    )
    op.alter_column(
        "messages",
        "conversation_id",
        existing_type=sa.UUID(),
        comment="Which conversation this message belongs to. Indexed: every message list query filters by conversation_id. CASCADE: conversation deleted → its messages are deleted too.",
        existing_comment="Which conversation this message belongs to.",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_conversations_property_id"), table_name="conversations")
    op.alter_column(
        "conversations",
        "property_id",
        existing_type=sa.UUID(),
        comment="The property this conversation is about. SET NULL: property deleted → conversation survives (messages are permanent). NULL for support conversations or admin-initiated threads.",
        existing_comment="The property this conversation is about. SET NULL: property deleted → conversation survives. NULL for support conversations or admin-initiated threads.",
        existing_nullable=True,
    )
    op.alter_column(
        "conversation_participants",
        "last_read_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the user last opened this conversation. NULL = never opened (all messages are unread). Updated by messaging_service.mark_as_read(). Used to calculate unread message count.",
        existing_comment="When the user last opened this conversation. NULL = never opened (all messages are unread).",
        existing_nullable=True,
    )
    op.alter_column(
        "conversation_participants",
        "user_id",
        existing_type=sa.UUID(),
        comment="Indexed separately from PK for 'find all conversations for user X' queries. RESTRICT: cannot delete user while they're a participant in conversations.",
        existing_comment="RESTRICT: cannot delete user who is in active conversations.",
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_participants",
        "conversation_id",
        existing_type=sa.UUID(),
        comment="CASCADE: conversation deleted → participant links are meaningless.",
        existing_comment="CASCADE: conversation deleted → participant links are removed.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
