"""reviews: simplify unique constraint to booking_id only

Revision ID: 1ed4eea9682c
Revises: 5f974f3f78fc
Create Date: 2026-07-31 15:55:27.481304+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1ed4eea9682c'
down_revision: str | None = '5f974f3f78fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_reviews', 'reviewer_id',
               existing_type=sa.UUID(),
               comment='The renter who wrote this review.',
               existing_comment='The renter who wrote this review. Named reviewer_id (not user_id) to avoid ambiguity with Review.user_id. Both refer to the renter. Part of UNIQUE constraint (reviewer_id, booking_id) — one review per booking.',
               existing_nullable=False)
    op.alter_column('agent_reviews', 'booking_id',
               existing_type=sa.UUID(),
               comment='The completed booking that enabled this review.',
               existing_comment='The completed booking that enabled this review. RESTRICT: reviews are permanent records. Part of UNIQUE constraint (reviewer_id, booking_id) — one review per booking.',
               existing_nullable=False)
    op.alter_column('agent_reviews', 'rating',
               existing_type=sa.INTEGER(),
               comment='Star rating from 1 to 5.',
               existing_comment='Star rating from 1 to 5. Integer only — no half-stars. Enforced by chk_agent_review_rating CHECK constraint.',
               existing_nullable=False)
    op.alter_column('agent_reviews', 'body',
               existing_type=sa.TEXT(),
               comment='Written review text. Optional.',
               existing_comment='Written review text. Optional — user may submit rating only.',
               existing_nullable=True)
    op.drop_constraint(op.f('uq_agent_review_per_booking'), 'agent_reviews', type_='unique')
    op.create_unique_constraint('uq_agent_review_per_booking', 'agent_reviews', ['booking_id'])
    op.alter_column('reviews', 'booking_id',
               existing_type=sa.UUID(),
               comment='The completed booking that enabled this review. RESTRICT: reviews are permanent records. Part of UNIQUE constraint — one property review per booking.',
               existing_comment='The completed booking that enabled this review. RESTRICT: reviews are permanent records. Part of UNIQUE constraint (user_id, booking_id) — one review per booking.',
               existing_nullable=False)
    op.drop_constraint(op.f('uq_review_per_booking'), 'reviews', type_='unique')
    op.create_unique_constraint('uq_property_review_per_booking', 'reviews', ['booking_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_property_review_per_booking', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('uq_review_per_booking'), 'reviews', ['user_id', 'booking_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('reviews', 'booking_id',
               existing_type=sa.UUID(),
               comment='The completed booking that enabled this review. RESTRICT: reviews are permanent records. Part of UNIQUE constraint (user_id, booking_id) — one review per booking.',
               existing_comment='The completed booking that enabled this review. RESTRICT: reviews are permanent records. Part of UNIQUE constraint — one property review per booking.',
               existing_nullable=False)
    op.drop_constraint('uq_agent_review_per_booking', 'agent_reviews', type_='unique')
    op.create_unique_constraint(op.f('uq_agent_review_per_booking'), 'agent_reviews', ['reviewer_id', 'booking_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('agent_reviews', 'body',
               existing_type=sa.TEXT(),
               comment='Written review text. Optional — user may submit rating only.',
               existing_comment='Written review text. Optional.',
               existing_nullable=True)
    op.alter_column('agent_reviews', 'rating',
               existing_type=sa.INTEGER(),
               comment='Star rating from 1 to 5. Integer only — no half-stars. Enforced by chk_agent_review_rating CHECK constraint.',
               existing_comment='Star rating from 1 to 5.',
               existing_nullable=False)
    op.alter_column('agent_reviews', 'booking_id',
               existing_type=sa.UUID(),
               comment='The completed booking that enabled this review. RESTRICT: reviews are permanent records. Part of UNIQUE constraint (reviewer_id, booking_id) — one review per booking.',
               existing_comment='The completed booking that enabled this review.',
               existing_nullable=False)
    op.alter_column('agent_reviews', 'reviewer_id',
               existing_type=sa.UUID(),
               comment='The renter who wrote this review. Named reviewer_id (not user_id) to avoid ambiguity with Review.user_id. Both refer to the renter. Part of UNIQUE constraint (reviewer_id, booking_id) — one review per booking.',
               existing_comment='The renter who wrote this review.',
               existing_nullable=False)
    # ### end Alembic commands ###
