"""notifications: inbox + user settings

Revision ID: 4c807274ed0e
Revises: 4b7953f3a0f5
Create Date: 2026-07-27 22:06:03.675682+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c807274ed0e"
down_revision: str | None = "4b7953f3a0f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversation_participants",
        "conversation_id",
        existing_type=sa.UUID(),
        comment="CASCADE: conversation deleted → participant links removed.",
        existing_comment="CASCADE: conversation deleted → participant links are removed.",
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_participants",
        "user_id",
        existing_type=sa.UUID(),
        comment="RESTRICT: cannot delete a user with active conversation history.",
        existing_comment="RESTRICT: cannot delete user who is in active conversations.",
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_participants",
        "last_read_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Updated when the user opens this conversation. NULL = never opened (all messages are unread).",
        existing_comment="When the user last opened this conversation. NULL = never opened (all messages are unread).",
        existing_nullable=True,
    )
    op.alter_column(
        "conversations",
        "property_id",
        existing_type=sa.UUID(),
        comment="The property this conversation is about. SET NULL: property deleted → conversation survives.",
        existing_comment="The property this conversation is about. SET NULL: property deleted → conversation survives. NULL for support conversations or admin-initiated threads.",
        existing_nullable=True,
    )
    op.alter_column(
        "notifications",
        "user_id",
        existing_type=sa.UUID(),
        comment="CASCADE: user deleted -> their notifications are disposable.",
        existing_comment="CASCADE: user deleted → their notifications are disposable. Indexed: notification feed queries filter by user_id.",
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "message",
        existing_type=sa.VARCHAR(length=1000),
        comment="Human-readable notification text shown in notification feed.",
        existing_comment="Human-readable notification text. Shown in notification feed.",
        existing_nullable=False,
    )
    op.drop_index("ix_notifications_is_read", table_name="notifications")
    op.drop_index("ix_notifications_user_id", table_name="notifications")
    op.create_index(
        "ix_notifications_unread_user",
        "notifications",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("is_read = false"),
    )
    op.create_index(
        "ix_notifications_user_created_at",
        "notifications",
        ["user_id", sa.text("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "user_notification_settings",
        "user_id",
        existing_type=sa.UUID(),
        comment="One settings row per user. UNIQUE enforces 1:1.",
        existing_comment="One settings row per user. UNIQUE enforces 1:1. CASCADE: user deleted → their settings are disposable.",
        existing_nullable=False,
    )
    op.alter_column(
        "user_notification_settings",
        "email_enabled",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Master switch for email notifications. If False, no emails sent.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "push_enabled",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Master switch for push notifications (FCM). If False, no pushes sent.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "sms_enabled",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Master switch for SMS notifications. Default False (SMS costs money). Only enabled for critical alerts (e.g. payment confirmation).",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_new_message",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="New message received in a conversation.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_booking_update",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Booking confirmed, rejected, or completed.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_listing_approved",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Property listing approved or rejected by admin.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_saved_search",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="New property matches a saved search alert.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_listing_expiry",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Listing is about to expire (7-day warning).",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_subscription",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Subscription expiring soon (3-day warning) or expired.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "marketing_email",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Marketing emails. Default False (opt-in). NDPR compliance.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_notification_settings",
        "marketing_sms",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Marketing SMS. Default False (opt-in). NDPR compliance.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_notification_settings",
        "marketing_sms",
        existing_type=sa.BOOLEAN(),
        comment="Marketing SMS. Default False (opt-in). NDPR compliance.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_notification_settings",
        "marketing_email",
        existing_type=sa.BOOLEAN(),
        comment="Marketing emails. Default False (opt-in). NDPR compliance.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_subscription",
        existing_type=sa.BOOLEAN(),
        comment="Subscription expiring soon (3-day warning) or expired.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_listing_expiry",
        existing_type=sa.BOOLEAN(),
        comment="Listing is about to expire (7-day warning).",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_saved_search",
        existing_type=sa.BOOLEAN(),
        comment="New property matches a saved search alert.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_listing_approved",
        existing_type=sa.BOOLEAN(),
        comment="Property listing approved or rejected by admin.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_booking_update",
        existing_type=sa.BOOLEAN(),
        comment="Booking confirmed, rejected, or completed.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "notify_new_message",
        existing_type=sa.BOOLEAN(),
        comment="New message received in a conversation.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "sms_enabled",
        existing_type=sa.BOOLEAN(),
        comment="Master switch for SMS notifications. Default False (SMS costs money). Only enabled for critical alerts (e.g. payment confirmation).",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "user_notification_settings",
        "push_enabled",
        existing_type=sa.BOOLEAN(),
        comment="Master switch for push notifications (FCM). If False, no pushes sent.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "email_enabled",
        existing_type=sa.BOOLEAN(),
        comment="Master switch for email notifications. If False, no emails sent.",
        existing_nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "user_notification_settings",
        "user_id",
        existing_type=sa.UUID(),
        comment="One settings row per user. UNIQUE enforces 1:1. CASCADE: user deleted → their settings are disposable.",
        existing_comment="One settings row per user. UNIQUE enforces 1:1.",
        existing_nullable=False,
    )
    op.drop_index("ix_notifications_user_created_at", table_name="notifications")
    op.drop_index(
        "ix_notifications_unread_user",
        table_name="notifications",
        postgresql_where=sa.text("is_read = false"),
    )
    op.create_index("ix_notifications_user_id", "notifications", ["user_id"], unique=False)
    op.create_index("ix_notifications_is_read", "notifications", ["is_read"], unique=False)
    op.alter_column(
        "notifications",
        "message",
        existing_type=sa.VARCHAR(length=1000),
        comment="Human-readable notification text. Shown in notification feed.",
        existing_comment="Human-readable notification text shown in notification feed.",
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "user_id",
        existing_type=sa.UUID(),
        comment="CASCADE: user deleted → their notifications are disposable. Indexed: notification feed queries filter by user_id.",
        existing_comment="CASCADE: user deleted -> their notifications are disposable.",
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "property_id",
        existing_type=sa.UUID(),
        comment="The property this conversation is about. SET NULL: property deleted → conversation survives. NULL for support conversations or admin-initiated threads.",
        existing_comment="The property this conversation is about. SET NULL: property deleted → conversation survives.",
        existing_nullable=True,
    )
    op.alter_column(
        "conversation_participants",
        "last_read_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="When the user last opened this conversation. NULL = never opened (all messages are unread).",
        existing_comment="Updated when the user opens this conversation. NULL = never opened (all messages are unread).",
        existing_nullable=True,
    )
    op.alter_column(
        "conversation_participants",
        "user_id",
        existing_type=sa.UUID(),
        comment="RESTRICT: cannot delete user who is in active conversations.",
        existing_comment="RESTRICT: cannot delete a user with active conversation history.",
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_participants",
        "conversation_id",
        existing_type=sa.UUID(),
        comment="CASCADE: conversation deleted → participant links are removed.",
        existing_comment="CASCADE: conversation deleted → participant links removed.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
