"""media: assets, property images, virtual tours

Revision ID: 5f974f3f78fc
Revises: 4c807274ed0e
Create Date: 2026-07-31 14:51:38.725253+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f974f3f78fc"
down_revision: str | None = "4c807274ed0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "property_images",
        "is_primary",
        existing_type=sa.BOOLEAN(),
        comment="The hero image for this property. Shown in search results and cards. Exactly one per property (enforced via partial index).",
        existing_comment="The hero image for this property. Shown in search results and cards. Exactly one per property (enforced in service layer).",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.create_index(
        "uq_property_primary_image",
        "property_images",
        ["property_id"],
        unique=True,
        postgresql_where=sa.text("is_primary IS TRUE"),
    )
    op.alter_column(
        "virtual_tours",
        "property_id",
        existing_type=sa.UUID(),
        comment="Which property this tour belongs to. CASCADE: property deleted → tour links are meaningless. Indexed for efficient property tour queries.",
        existing_comment="Which property this tour belongs to. CASCADE: property deleted → tour links are meaningless.",
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_virtual_tours_property_id"), "virtual_tours", ["property_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_virtual_tours_property_id"), table_name="virtual_tours")
    op.alter_column(
        "virtual_tours",
        "property_id",
        existing_type=sa.UUID(),
        comment="Which property this tour belongs to. CASCADE: property deleted → tour links are meaningless.",
        existing_comment="Which property this tour belongs to. CASCADE: property deleted → tour links are meaningless. Indexed for efficient property tour queries.",
        existing_nullable=False,
    )
    op.drop_index(
        "uq_property_primary_image",
        table_name="property_images",
        postgresql_where=sa.text("is_primary IS TRUE"),
    )
    op.alter_column(
        "property_images",
        "is_primary",
        existing_type=sa.BOOLEAN(),
        comment="The hero image for this property. Shown in search results and cards. Exactly one per property (enforced in service layer).",
        existing_comment="The hero image for this property. Shown in search results and cards. Exactly one per property (enforced via partial index).",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###
