# alembic/env.py

"""
alembic/env.py
──────────────────────────────────────────────────────────────────────────────
Sync Alembic environment, wired to:
  - app.core.config.settings   → DATABASE_URL (overrides alembic.ini)
  - app.db.base_all            → imports all 27 models, exposes Base.metadata

Uses psycopg 3 in SYNC mode. Alembic is a CLI tool that runs once and
exits — no benefit to async. Sync mode also avoids Windows ProactorEventLoop
issues with psycopg 3 async.

──────────────────────────────────────────────────────────────────────────────
KNOWN GOTCHAS — read before running autogenerate
──────────────────────────────────────────────────────────────────────────────

1. PostGIS creates a `spatial_ref_sys` system table.
   Without filtering, autogenerate will try to DROP it on every run.
   The `include_object()` filter below excludes it.

2. ENUM types — Alembic handles these automatically.
   Models use sa.Enum(..., name="type_name") with NO create_type flag
   (defaults to True). Alembic's DDL runner deduplicates CREATE TYPE
   per named type within a single migration run via an internal memo
   system — each type is emitted exactly once even when used across
   multiple tables. No manual CREATE TYPE statements needed.

3. The PostGIS GiST spatial index on properties (latitude/longitude) is
   NOT detected by autogenerate. Add manually to the initial migration:

       op.execute('''
           CREATE INDEX idx_properties_location ON properties USING GiST (
               ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
           )
       ''')

   And in downgrade():
       op.execute("DROP INDEX IF EXISTS idx_properties_location")

4. PostGIS extension and uuid-ossp must exist before any spatial index
   or UUID default is used. Add as the very first operations in the
   initial migration:

       op.execute('CREATE EXTENSION IF NOT EXISTS "postgis"')
       op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

5. updated_at triggers (one per TimestampMixin table) are NOT
   autogenerated. Add the trigger function once, then one CREATE TRIGGER
   per table — see app/db/base.py for the trigger SQL.

6. DROP TYPE in downgrade migrations is NOT autogenerated. If a future
   migration removes a column that is the last use of an enum type, add
   op.execute("DROP TYPE IF EXISTS type_name") manually to downgrade().

Steps 3, 4, 5 only apply to the INITIAL migration. Every migration
after that is a normal model change → autogenerate → review → apply.
"""
import sys
from pathlib import Path

# ── Make 'app' importable from anywhere ──────────────────────────────────────
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# ── Import all models (side-effect: registers 27 tables with Base.metadata) ──
from app.db.base_all import Base  # noqa: F401

# ── Import settings for database URL ─────────────────────────────────────────
from app.core.config import settings

# ── Alembic Config object ────────────────────────────────────────────────────
config = context.config

# Override alembic.ini's sqlalchemy.url with the live setting from .env.
# DATABASE_URL is configured in ONE place (app/core/config.py),
# never duplicated in alembic.ini.
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Target metadata — this is what autogenerate diffs your DB against.
target_metadata = Base.metadata


# ── PostGIS / system-object filtering ────────────────────────────────────────

_EXTENSION_OWNED_TABLES = {
    "spatial_ref_sys",  # Created by the postgis extension
}


def include_object(object, name, type_, reflected, compare_to):
    """
    Alembic autogenerate filter. Return False to exclude an object
    from the diff entirely (it will never appear in a migration).
    """
    if type_ == "table" and name in _EXTENSION_OWNED_TABLES:
        return False
    return True


# ── Offline mode ─────────────────────────────────────────────────────────────

def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode — emits SQL to stdout/a file.
    Usage: alembic upgrade head --sql > migration.sql
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


# ── Online mode (sync — no async needed for CLI tool) ────────────────────────

def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode.
    Uses sync engine directly — no async bridging, no event loop issues.
    Works on Windows, Linux, macOS without any platform-specific workarounds.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,  # Don't pool connections for migrations
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
            compare_server_default=True,
        )

        with context.begin_transaction():
            context.run_migrations()


# ── Dispatch ─────────────────────────────────────────────────────────────────

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()